# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# https://docs.scrapy.org/en/latest/topics/items.html

import scrapy


class YaodaoyunItem(scrapy.Item):
    productId = scrapy.Field()
    courseId = scrapy.Field()
    productName = scrapy.Field()
    productType = scrapy.Field()
    startTime = scrapy.Field()
    endTime = scrapy.Field()
    description = scrapy.Field()
    provider = scrapy.Field()
    score = scrapy.Field()
    scoreLevel = scrapy.Field()
    learnerCount = scrapy.Field()
    lessonCount = scrapy.Field()
    imgUrl = scrapy.Field()
    bigImgUrl = scrapy.Field()
    lectorName = scrapy.Field()
    originalPrice = scrapy.Field()
    discountPrice = scrapy.Field()
    discountRate = scrapy.Field()
    forumTagLector = scrapy.Field()
    tagLectorTime = scrapy.Field()
    schoolShortName = scrapy.Field()
    tagIap = scrapy.Field()
    gmtModified = scrapy.Field()
    firstPublishTime = scrapy.Field()
    displayType = scrapy.Field()
    courseCardProps = scrapy.Field()
    published = scrapy.Field()
    activityIds = scrapy.Field()
    isPromStatus = scrapy.Field()
    machineGrade = scrapy.Field()
    vipContentType = scrapy.Field()
    vipStartTime = scrapy.Field()
    vipEndTime = scrapy.Field()
    vipPrice = scrapy.Field()
    viewCount = scrapy.Field()
    termType = scrapy.Field()
    compositeType = scrapy.Field()
    parentName = scrapy.Field()
    scheduleType = scrapy.Field()
    advertiseSearchUuid = scrapy.Field()
    advertiseFlag = scrapy.Field()
    webOneDesc = scrapy.Field()
    categoryNames = scrapy.Field()
    total_nums = scrapy.Field()
    category_id = scrapy.Field()
    crawl_time = scrapy.Field()
    browseCount = scrapy.Field()
    resourceType = scrapy.Field()
    targetUrl = scrapy.Field()
    searchItemType = scrapy.Field()
    belongToId = scrapy.Field()
    appType = scrapy.Field()
    actionScene = scrapy.Field()
    activityUrl = scrapy.Field()
    isTopGrade = scrapy.Field()
    totalCount = scrapy.Field()
    discountCouponId = scrapy.Field()
    discountCouponType = scrapy.Field()
    remainingCount = scrapy.Field()
    instructor = scrapy.Field()
    subTitle = scrapy.Field()
    recommendRequestId = scrapy.Field()
    recommendAlgInfo = scrapy.Field()
    appImgUrl = scrapy.Field()
    webImgUrl = scrapy.Field()
    wapImgUrl = scrapy.Field()
    webImgColor = scrapy.Field()
    bannerTitle = scrapy.Field()
    capsuleImgUrl = scrapy.Field()
    popupImgUrl = scrapy.Field()
    smallWindowPicUrl = scrapy.Field()
    readyStatus = scrapy.Field()
    cornerMark = scrapy.Field()
    weight = scrapy.Field()
    courseCount = scrapy.Field()
    termSchedule = scrapy.Field()
    topGrade = scrapy.Field()
    categoryId = scrapy.Field()
    breadcrumb_dict = scrapy.Field()

class lessonItem(scrapy.Item):
    category_id = scrapy.Field()
    crawl_time = scrapy.Field()
    audioTime = scrapy.Field()
    browseCount = scrapy.Field()
    chapterId = scrapy.Field()
    description = scrapy.Field()
    duration = scrapy.Field()
    finishedTime = scrapy.Field()
    gmtCreate = scrapy.Field()
    hasReferences = scrapy.Field()
    id = scrapy.Field()
    lastLearnedTime = scrapy.Field()
    lastUpdateTime = scrapy.Field()
    learnMark = scrapy.Field()
    learnable = scrapy.Field()
    learnedIndex = scrapy.Field()
    lessonBookContent = scrapy.Field()
    lessonName = scrapy.Field()
    level = scrapy.Field()
    liveContent = scrapy.Field()
    liveInfo = scrapy.Field()
    parentId = scrapy.Field()
    photoUrl = scrapy.Field()
    position = scrapy.Field()
    startTime = scrapy.Field()
    status = scrapy.Field()
    type = scrapy.Field()
    videoTime = scrapy.Field()
    viewPrivilege = scrapy.Field()
    wapUrl = scrapy.Field()
    boughtInfo = scrapy.Field()
    discountPrice = scrapy.Field()
    fee = scrapy.Field()
    boughtInfo = scrapy.Field()
    courseid = scrapy.Field()
